# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161028_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='imdb_ratings',
            new_name='csv_ratings',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='imdb_ratings_used',
            new_name='last_updated_csv_ratings',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_updated',
            new_name='last_updated_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ratings_last_updated',
            new_name='last_updated_rss_ratings',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_updated_rss_watchlist',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
