version: '3'

services:
  movie-backend:
    container_name: movie-backend-container
    image: reryk/movie-backend
    build: ./src
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env.dev
    volumes:
      - ./src:/code
      - media:/movie-media
    ports:
      - "8000:8000"
    depends_on:
      - movie-database
      - redis

  movie-database:
    container_name: movie-database-container
    image: postgres:9.4
    restart: always
    env_file: .env.dev
    volumes:
      - /opt/postgres/movie:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - 5432

  redis:
    container_name: movie-redis-container
    image: "redis:alpine"

  celery:
    container_name: movie-celery-container
    build: ./src
    command: celery -A mysite worker -l info
    env_file: .env.dev
    volumes:
      - ./src:/code
      - media:/movie-media
    depends_on:
      - movie-database
      - redis

  celery-beat:
    container_name: movie-celery-beat-container
    build: ./src
    command: celery -A mysite beat -l info
    volumes:
      - ./src:/code
    depends_on:
      - movie-database
      - redis

volumes:
  media: