version: '3'

services:
  movie-nginx:
    container_name: movie-nginx
    image: registry.eryk.io/movie-nginx
    build: ./nginx
    env_file: .env.prod
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=movie.eryk.io
      - LETSENCRYPT_HOST=movie.eryk.io
    volumes:
      - media:/movie-media
      - static:/movie-static
    expose:
      - 80
    depends_on:
      - movie-backend

  movie-backend:
    container_name: movie-backend
    image: registry.eryk.io/movie-backend
    build: ./src
    restart: unless-stopped
    command: bash -c "python manage.py collectstatic --noinput && gunicorn mysite.wsgi -b 0.0.0.0:9000 --workers 2"
    env_file: .env.prod
    volumes:
      - ./src:/code
      - media:/movie-media
      - static:/movie-static
    expose:
      - 9000
    depends_on:
      - movie-database
      - redis

  movie-database:
    container_name: movie-database
    image: postgres:9.4
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - /opt/postgres/movie:/var/lib/postgresql/data
    expose:
      - 5432

  movie-redis:
    container_name: movie-redis
    image: "redis:alpine"
    restart: unless-stopped

  movie-celery:
    container_name: movie-celery
    image: registry.eryk.io/movie-backend
    command: celery -A mysite worker -l info
    env_file: .env.prod
    volumes:
      - media:/movie-media
    depends_on:
      - movie-backend
      - movie-redis
    restart: unless-stopped

  movie-celery-beat:
    container_name: movie-celery-beat
    image: registry.eryk.io/movie-backend
    command: celery -A mysite beat -l info
    depends_on:
      - movie-backend
      - movie-redis
    restart: unless-stopped

volumes:
  media:
  static:

networks:
  default:
    external:
      name: nginx-proxy
