# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.PositiveIntegerField(blank=True, null=True)),
                ('nick', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_date',),
            },
        ),
    ]
