# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nick', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-added_date',),
            },
        ),
    ]
