# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='const',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
