# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20160726_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='const',
            field=models.CharField(max_length=50, unique=True, verbose_name='IMDb URL or ID'),
        ),
    ]
