# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20161025_2102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set([('user', 'title')]),
        ),
    ]
