# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_auto_20160726_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
