# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_auto_20160726_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
