# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_auto_20160726_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='date_insert',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='nick',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='year',
        ),
    ]
