# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20160726_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 26, 21, 19, 43, 888058, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='date_insert',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 26, 21, 19, 50, 192419, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='nick',
            field=models.CharField(default=datetime.datetime(2016, 7, 26, 21, 20, 0, 862029, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
