# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_auto_20160726_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='const',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='date_insert',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='nick',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='year',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='c',
            field=models.TextField(default=datetime.datetime(2016, 7, 26, 21, 29, 1, 123930, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
