# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_auto_20160726_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
