# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='title',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ()},
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
