# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='poster_backdrop_title',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='title',
            name='poster_backdrop_user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='title',
            name='poster_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='title',
            name='poster_small',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
