# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models

import shared.helpers
import titles.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20171130_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='poster_backdrop_title',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_random_file_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_backdrop_user',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_random_file_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_card',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_random_file_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_small',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_random_file_path),
        ),
    ]
