# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shared.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20171201_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('number', models.SmallIntegerField(default=1)),
                ('episodes', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='job',
            field=models.IntegerField(blank=True, choices=[(0, 'Director'), (1, 'Screenplay'), ('Creator', 2)], null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_backdrop_title',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_instance_file_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_backdrop_user',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_instance_file_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_card',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_instance_file_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_small',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_instance_file_path),
        ),
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title'),
        ),
    ]
