# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20171210_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='picture_path',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='poster_path',
            new_name='image_path',
        ),
    ]
