# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20171201_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('titles', models.ManyToManyField(blank=True, related_name='collection', to='titles.Title')),
            ],
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='titles.Title'),
        ),
    ]
