# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20171204_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='recommends', to='titles.Title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='similars', to='titles.Title'),
        ),
        migrations.AddField(
            model_name='popular',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='popular', to='titles.Title'),
        ),
    ]
