# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20171205_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popular',
            options={'ordering': ('-update_date',)},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='titles',
        ),
        migrations.AddField(
            model_name='title',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='titles.Collection'),
        ),
        migrations.AlterField(
            model_name='popular',
            name='update_date',
            field=models.DateField(unique=True),
        ),
    ]
