# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20171213_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(unique=True)),
                ('titles', models.ManyToManyField(blank=True, related_name='upcoming', to='titles.Title')),
            ],
            options={
                'ordering': ('-update_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='nowplaying',
            options={'ordering': ('-update_date',)},
        ),
    ]
