# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import shared.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20171207_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=shared.helpers.get_instance_file_path),
        ),
        migrations.AddField(
            model_name='person',
            name='picture_path',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
