# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20171209_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casttitle',
            options={'ordering': ('-order',)},
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
