# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20171213_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='titles',
        ),
        migrations.AddField(
            model_name='popular',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='popular_movies', to='titles.Title'),
        ),
        migrations.AddField(
            model_name='popular',
            name='tv',
            field=models.ManyToManyField(blank=True, related_name='popular_tv', to='titles.Title'),
        ),
    ]
