# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_auto_20171213_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowplaying',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popular',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
