# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_title_being_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
