# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0015_auto_20171226_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-release_date', '-update_date')},
        ),
        migrations.RenameField(
            model_name='title',
            old_name='being_updated',
            new_name='getting_details',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='updated',
            new_name='has_details',
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.IntegerField(blank=True, choices=[(None, ''), (0, 'Movie'), (1, 'TV Show')], null=True),
        ),
    ]
