# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0016_auto_20171228_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='titles.Collection'),
        ),
    ]
