# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0019_auto_20180101_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casttitle',
            name='character',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
