# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0020_auto_20180102_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together=set([('imdb_id', 'tmdb_id')]),
        ),
    ]
