# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='list',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('order', '-create_date')},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ('-create_date',)},
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='added_date',
        ),
        migrations.AddField(
            model_name='favourite',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourite',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
