# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20171223_1656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([]),
        ),
    ]
