# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=30)),
                ('rate_imdb', models.CharField(max_length=30)),
                ('runtime', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('votes', models.CharField(max_length=30)),
                ('director', models.ManyToManyField(to='movie.Director')),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Type'),
        ),
    ]
