# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Entry',
        ),
    ]
