# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='user_followed',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='userfollow',
            old_name='user_follower',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=set([('follower', 'followed')]),
        ),
    ]
