# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_csv_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_updated_csv_ratings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated_rss_ratings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated_rss_watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
