# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('rate_date', models.DateField()),
                ('inserted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-rate_date', '-inserted_date'),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=9, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('rate_imdb', models.FloatField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('url_poster', models.URLField(blank=True, null=True)),
                ('url_imdb', models.URLField(blank=True, null=True)),
                ('url_tomato', models.URLField(blank=True, null=True)),
                ('tomato_meter', models.IntegerField(blank=True, null=True)),
                ('tomato_rating', models.FloatField(blank=True, null=True)),
                ('tomato_reviews', models.IntegerField(blank=True, null=True)),
                ('tomato_fresh', models.IntegerField(blank=True, null=True)),
                ('tomato_rotten', models.IntegerField(blank=True, null=True)),
                ('tomato_user_meter', models.IntegerField(blank=True, null=True)),
                ('tomato_user_rating', models.FloatField(blank=True, null=True)),
                ('tomato_user_reviews', models.IntegerField(blank=True, null=True)),
                ('tomatoConsensus', models.TextField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=300)),
                ('img', models.ImageField(blank=True, null=True, upload_to='poster')),
                ('img_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('-inserted_date',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('imdb', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
            ],
            options={
                'ordering': ('-added_date',),
            },
        ),
    ]
