# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171218_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='csv_ratings',
        ),
    ]
