# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('rate_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-rate_date',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=9, unique=True)),
                ('name', models.TextField()),
                ('rate_imdb', models.FloatField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('url_poster', models.URLField(blank=True, null=True)),
                ('url_imdb', models.URLField(blank=True, null=True)),
                ('url_tomato', models.URLField(blank=True, null=True)),
                ('tomato_meter', models.IntegerField(blank=True, null=True)),
                ('tomato_rating', models.FloatField(blank=True, null=True)),
                ('tomato_reviews', models.IntegerField(blank=True, null=True)),
                ('tomato_fresh', models.IntegerField(blank=True, null=True)),
                ('tomato_rotten', models.IntegerField(blank=True, null=True)),
                ('tomato_user_meter', models.IntegerField(blank=True, null=True)),
                ('tomato_user_rating', models.FloatField(blank=True, null=True)),
                ('tomato_user_reviews', models.IntegerField(blank=True, null=True)),
                ('tomatoConsensus', models.TextField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='poster')),
                ('watch_again_date', models.DateField(blank=True, null=True)),
                ('actor', models.ManyToManyField(to='movie.Actor')),
                ('director', models.ManyToManyField(to='movie.Director')),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
            options={
                'ordering': ('-rating__rate_date', '-inserted_date'),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('imdb', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_date',),
            },
        ),
        migrations.AddField(
            model_name='title',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Type'),
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Title'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourite',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Title'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([('user', 'title', 'added_date', 'imdb')]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'title', 'rate', 'rate_date')]),
        ),
    ]
