# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(blank=True, max_length=30, null=True)),
                ('rate', models.CharField(blank=True, max_length=30, null=True)),
                ('rate_date', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=30, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=30, null=True)),
                ('rate_imdb', models.CharField(blank=True, max_length=30, null=True)),
                ('rate_date', models.CharField(blank=True, max_length=30, null=True)),
                ('runtime', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('release_date', models.CharField(blank=True, max_length=30, null=True)),
                ('votes', models.CharField(blank=True, max_length=30, null=True)),
                ('url_imdb', models.URLField(blank=True, null=True)),
                ('url_poster', models.URLField(blank=True, null=True)),
                ('url_tomato', models.URLField(blank=True, null=True)),
                ('tomato_user_meter', models.CharField(blank=True, max_length=30, null=True)),
                ('tomato_user_rate', models.CharField(blank=True, max_length=30, null=True)),
                ('tomato_user_reviews', models.CharField(blank=True, max_length=30, null=True)),
                ('tomatoConsensus', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('inserted_by_updater', models.BooleanField(default=False)),
                ('inserted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('director', models.ManyToManyField(to='movie.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=30, unique=True)),
                ('number', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=30, null=True)),
                ('rate_imdb', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('new_inserted', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_archived', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Season'),
        ),
        migrations.AddField(
            model_name='entry',
            name='genre',
            field=models.ManyToManyField(to='movie.Genre'),
        ),
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Type'),
        ),
    ]
