# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20161013_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='url_poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
