# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160725_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
