# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160727_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rate_imdb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
