# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20161103_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-rate_date', '-inserted_date')},
        ),
        migrations.AddField(
            model_name='rating',
            name='inserted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
