# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20161015_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
