# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170312_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='img_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
