# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_watchlist_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ('-added_date',)},
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
