# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_entry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
