# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20160728_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
