# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20161015_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([('user', 'title', 'added_date', 'imdb')]),
        ),
    ]
