# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170325_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
