# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_entry_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='watch_again',
            field=models.BooleanField(default=False),
        ),
    ]
