# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20161015_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-rate_date',)},
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
