# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20160831_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='watch_again_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
