# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20160901_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='watch_again',
        ),
    ]
