# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='slug',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='const',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
