# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20160916_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='added_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='const',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([('const', 'added_date')]),
        ),
    ]
