# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_auto_20160916_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='added_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='name',
            field=models.TextField(),
        ),
    ]
