# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_watchlist_deleted_after_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='active',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='deleted_after_watched',
        ),
    ]
