# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_auto_20160921_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='set_to_delete',
            field=models.BooleanField(default=0),
        ),
    ]
