# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_watchlist_set_to_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added_date']},
        ),
    ]
