# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20161008_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestTitles',
            new_name='Favourite',
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-order']},
        ),
    ]
