# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20161008_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='const',
        ),
        migrations.AddField(
            model_name='favourite',
            name='entry',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='movie.Entry'),
            preserve_default=False,
        ),
    ]
