# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_auto_20161008_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={},
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='entry',
        ),
        migrations.AddField(
            model_name='favourite',
            name='const',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
