# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_auto_20161009_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
