# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_auto_20161011_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url_imdb',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url_poster',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url_tomato',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
