# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_auto_20161011_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='const',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='rate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='const',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='release_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='runtime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tomato_user_meter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tomato_user_rate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tomato_user_reviews',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='votes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='const',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='rate_imdb',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='const',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='const',
            field=models.CharField(max_length=150),
        ),
    ]
