# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20171121_2146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='titles',
            field=models.ManyToManyField(blank=True, to='titles.Title'),
        ),
        migrations.RemoveField(
            model_name='list',
            name='default',
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([('name', 'user')]),
        ),
    ]
