# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '0015_auto_20171226_1052'),
        ('lists', '0003_auto_20171226_1050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('user', 'title')]),
        ),
    ]
