# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180101_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
