# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='title',
            name='poster_backdrop_title',
        ),
        migrations.RemoveField(
            model_name='title',
            name='poster_backdrop_user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='poster_card',
        ),
        migrations.RemoveField(
            model_name='title',
            name='poster_small',
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_path',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
