# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20171210_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(unique=True)),
                ('persons', models.ManyToManyField(blank=True, related_name='popular', to='titles.Person')),
            ],
            options={
                'ordering': ('-update_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-number',)},
        ),
    ]
