# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '0012_title_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyWatchingTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.IntegerField(blank=True, choices=[(None, ''), (0, 'Movie'), (1, 'TV Shows')], null=True),
        ),
        migrations.AddField(
            model_name='currentlywatchingtv',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title'),
        ),
        migrations.AddField(
            model_name='currentlywatchingtv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
