# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0013_auto_20171220_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-rate_date', '-create_date')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='inserted_date',
        ),
        migrations.AddField(
            model_name='rating',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
