# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0018_remove_title_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_date',
            field=models.DateField(db_index=True),
        ),
    ]
