name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#       run: docker-compose -f docker-compose.prod.yml build
    -
      name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
