name: Push Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: erykio/private
        ref: master
        token: ${{ secrets.ACCESS_TOKEN }}
        path: private

    - name: Copy docker-compose files
      run: cp private/apps/movie-website/docker-compose.prod.yml . && cp private/apps/movie-website/.env.prod .

    - name: Build images
      run: docker-compose -f docker-compose.prod.yml build
      
    - name: Push images
      run: docker-compose -f docker-compose.prod.yml push
