name: Release

on:
  push:
    branches: [ master ]

env:
  APP_IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/movie-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Build app image
        run: |
          docker build --tag ${{ env.APP_IMAGE_NAME }}:latest .

      - name: Push
        run: |
          docker push ${{ env.APP_IMAGE_NAME }}:latest
